# Generated by Django 5.2.4 on 2025-07-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('icono', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion_corta', models.TextField()),
                ('descripcion_larga', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateField()),
                ('duracion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, choices=[('desarrollo', 'En Desarrollo'), ('completado', 'Completado'), ('mantenimiento', 'Mantenimiento')], max_length=20, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('url_demo', models.URLField(blank=True, null=True)),
                ('url_github', models.URLField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(default='general', max_length=50)),
                ('tecnologias', models.ManyToManyField(blank=True, to='proyectos.tecnologia')),
            ],
        ),
    ]
