# Generated by Django 4.2.15 on 2026-06-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_fix_imagen_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='proyectos/galeria/')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_galeria', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Imagen de proyecto',
                'verbose_name_plural': 'Imágenes de proyecto',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
